
```{r}
##final standins 16/17 along with potential explanatory variables
final.standings<- c('Chelsea','Tottenham','Man City','Liverpool','Arsenal','Man United','Everton', 'Southampton','Bournemouth','West Brom','West Ham','Leicester','Stoke','Crystal Palace','Swansea','Burnley','Watford', 'Hull','Middlesbrough','Sunderland')
wins<- c(30,26,23,22,23,18,17,12,12,12,12,12,11,12,12,11,11,9,5,6)
goals.for.a.game<- c(85,86,80,78,77,54,62,41,55,43,47,48,41,50,45,39,40,37,27,29)/38
goals.against.a.game<- c(33,26,39,42,44,29,44,48,67,51,64,63,56,63,70,55,68,80,53,69)/38
group<- c(rep("Top 5",5), rep("Middle 10",10), rep("Bottom 5 ",5))

table<- data.frame(final.standings, group, wins, goals.for.a.game, goals.against.a.game)
top5<- table[1:5,]
middle10<- table[6:15,]
bottom5<- table[16:20,]
da<- data.frame(meanz=c(2.137, 1.279, 0.905),group=c("Top 5", "Middle 10", "Bottom 5"))
ggplot(data=table, aes(x=goals.for.a.game, fill=group)) +
  geom_density(alpha=0.7) +
  geom_vline(data=da, aes(xintercept=meanz, color=group),linetype="dashed", show.legend = FALSE) +
  scale_fill_manual(values=c("magenta", "blue", "darkgreen")) +
  scale_color_manual(values=c("magenta", "blue", "darkgreen")) +
  xlim(0.4, 2.5) +
  xlab("Average goals scored")

da<- data.frame(meanz=c(0.968, 1.461,1.71),group=c("Top 5", "Middle 10", "Bottom 5"))
ggplot(data=table, aes(x=goals.against.a.game, fill=group)) +
  geom_density(alpha=0.6) +
  geom_vline(data=da, aes(xintercept=meanz, color=group),linetype="dashed", show.legend = FALSE) +
  scale_fill_manual(values=c("magenta", "blue", "darkgreen")) +
  scale_color_manual(values=c("magenta", "blue", "darkgreen")) +
  xlim(0.4, 2.5) +
  xlab("Average goals conceded")


##ACTUAL DENSITY COMPARED WITH ITS APPROXIMATE NORMAL DISTRIBUTION: TOP 5- GOALS SCORED PER GAME

norm_data<- rnorm(n=10000000, mean = mean(top5$goals.for.a.game), sd=sd(top5$goals.for.a.game))
type<- c(rep("Actual density",5), rep("Approximate normal", 10000000))
points<- c(top5$goals.for.a.game, norm_data)
plot.data=data.frame(type, points)
ggplot(data = plot.data, aes(x=points, group=type, fill=type)) +
  geom_density(alpha=0.6) +
  xlim(1.8,2.5) +
  labs(title = "Top 5 teams") +
  xlab("Average goals scored") +
  scale_fill_manual(values=c("darkgreen", "deepskyblue4")) +
  theme(legend.title = element_blank()) +
  annotate("text", x=2.4, y=3, label= expression(p*"=0.31"), color="black")

##ACTUAL DENSITY COMPARED WITH ITS APPROXIMATE NORMAL DISTRIBUTION: MIDDLE 10- GOALS SCORED PER GAME
norm_data<- rnorm(n=1000000, mean = mean(middle10$goals.for.a.game), sd=sd(middle10$goals.for.a.game))
type<- c(rep("Actual density", 10), rep("Approximate normal", 1000000))
points<- c(middle10$goals.for.a.game, norm_data)
plot.data=data.frame(type, points)
ggplot(data = plot.data, aes(x=points, group=type, fill=type)) +
  geom_density(alpha=0.6) +
  xlim(0.8,1.9) +
  labs(title = "Middle 10 teams") +
  xlab("Average goals scored") +
  scale_fill_manual(values=c("blue", "deepskyblue4")) +
  theme(legend.title = element_blank()) +
  annotate("text", x=1.75, y=2, label= expression(p~"=0.48"), color="black")

##ACTUAL DENSITY COMPARED WITH ITS APPROXIMATE NORMAL DISTRIBUTION: BOTTOM 5- GOALS SCORED PER GAME
norm_data<- rnorm(n=1000000, mean = mean(bottom5$goals.for.a.game), sd=sd(bottom5$goals.for.a.game))
type<- c(rep("Actual density", 5), rep("Approximate normal", 1000000))
points<- c(bottom5$goals.for.a.game, norm_data)
plot.data=data.frame(type, points)
ggplot(data = plot.data, aes(x=points, group=type, fill=type)) +
  geom_density(alpha=0.6) +
  xlim(0.4,1.4) +
  labs(title = "Bottom 5 teams") +
  xlab("Average goals scored") +
  scale_fill_manual(values=c("magenta", "deepskyblue4")) +
  theme(legend.title = element_blank()) +
  annotate("text", x=1.3, y=2, label= expression(p~"=0.21"), color="black")

##ACTUAL DENSITY COMPARED WITH ITS APPROXIMATE NORMAL DISTRIBUTION: TOP 5- GOALS CONCEDED PER GAME
norm_data<- rnorm(n=100000, mean = mean(top5$goals.against.a.game), sd=sd(top5$goals.against.a.game))
type<- c(rep("Actual Density", 5), rep("Approximate normal", 100000))
points<- c(top5$goals.against.a.game, norm_data)
plot.data=data.frame(type, points)
ggplot(data = plot.data, aes(x=points, group=type, fill=type)) +
  geom_density(alpha=0.6) +
  xlim(0.4,1.5) +
  labs(title = "Top 5 teams") +
  xlab("Goals conceded per game")

##ACTUAL DENSITY COMPARED WITH ITS APPROXIMATE NORMAL DISTRIBUTION: MIDDLE 10- GOALS CONCEDED PER GAME
norm_data<- rnorm(n=100000, mean = mean(middle10$goals.against.a.game), sd=sd(middle10$goals.against.a.game))
type<- c(rep("Actual Density", 10), rep("Approximate normal", 100000))
points<- c(middle10$goals.against.a.game, norm_data)
plot.data=data.frame(type, points)
ggplot(data = plot.data, aes(x=points, group=type, fill=type)) +
  geom_density(alpha=0.6) +
  xlim(0.4,2.4) +
  labs(title = "Middle 10 teams") +
  xlab("Goals conceded per game")

##ACTUAL DENSITY COMPARED WITH ITS APPROXIMATE NORMAL DISTRIBUTION: BOTTOM 5- GOALS CONCEDED PER GAME
norm_data<- rnorm(n=100000, mean = mean(bottom5$goals.against.a.game), sd=sd(bottom5$goals.against.a.game))
type<- c(rep("Actual Density", 5), rep("Approximate normal", 100000))
points<- c(bottom5$goals.against.a.game, norm_data)
plot.data=data.frame(type, points)
ggplot(data = plot.data, aes(x=points, group=type, fill=type)) +
  geom_density(alpha=0.6) +
  xlim(0.9,2.6) +
  labs(title = "Bottom 5 teams") +
  xlab("Goals conceded per game")

##ANNOTATE THE PVALUES FROM SHAPIRO TESTS??????????
##CALCULATE FORM VECTORS???????????

##SHAPIRO WILK TESTS FOR NORMALITY- NO SIGNIFICANT P VALUES- ALL DATA IS ASSUMED TO BE NORMAL
shapiro.test(top5$goals.for.a.game)
shapiro.test(middle10$goals.for.a.game)
shapiro.test(bottom5$goals.for.a.game)
shapiro.test(top5$goals.against.a.game)
shapiro.test(middle10$goals.against.a.game)
shapiro.test(bottom5$goals.against.a.game)

```



```{r}

##F TEST BETWEEN ALL GROUPS TO CHECK IF VARIANCES ARE SIGNIFICANTLY DIFFERENT- NO SIGNIFICANT PVALS- ALL VARIANCES ASSUMED EQUAL

var.test(top5$goals.for.a.game, middle10$goals.for.a.game, alternative = "two.sided")$p.value
var.test(top5$goals.for.a.game, bottom5$goals.for.a.game, alternative = "two.sided")$p.value
var.test(bottom5$goals.for.a.game, middle10$goals.for.a.game, alternative = "two.sided")$p.value
var.test(top5$goals.against.a.game, middle10$goals.against.a.game, alternative = "two.sided")$p.value
var.test(top5$goals.against.a.game, bottom5$goals.against.a.game, alternative = "two.sided")$p.value
var.test(bottom5$goals.against.a.game, middle10$goals.against.a.game, alternative = "two.sided")$p.value

##GOALS FOR & GOALS AGAINST ARE NORMAL AND VARIANCES ARE SIMILAR FOR THE 3 GROUPS (ANOVA TEST IS APPROPRIATE) 

```

```{r}
##ANALYSIS OF VARIANCE AND POSTHOC TUKEY FOR GOALS SCORED PER GAME- SIGNIFICANT P VALUES => STRONGER TEAM=HIGHER MEAN GOALS
an0va1<- aov(table$goals.for.a.game~table$group)
summary(an0va1)
options(digits = 10)
TukeyHSD(x=an0va1, 'table$group',conf.level=0.95)


##ANALYSIS OF VARIANCE AND POSTHOC TUKEY FOR GOALS SCORED PER GAME- SOME! EVIDENCE THAT STRONGER TEAMS CONCEDE LESS GOALS
an0va2<- aov(table$goals.against.a.game~table$group)
summary(an0va2)
TukeyHSD(x=an0va2, 'table$group',conf.level=0.95)


```

